# Copyright 2026 Shumpei Shiina.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import math
import secrets
from typing import Any

import egrpc
import jax
import jax.extend.core as jax_core
import jax.numpy as jnp
from jax.experimental import io_callback
import numpy as np

from ..mechanism import spend_gaussian
from ..realexpr import joint_l2_max
from ..util import DPError
from .array import SensitiveArray


def _fresh_key_data() -> np.ndarray[Any, np.dtype[np.uint32]]:
    return np.frombuffer(secrets.token_bytes(8), dtype=np.uint32)


def _fresh_noise_key() -> jax.Array:
    key_data = io_callback(
        _fresh_key_data,
        jax.ShapeDtypeStruct(  # type: ignore[no-untyped-call]
            (2,),
            jnp.uint32,
        ),
        ordered=True,
    )
    return jax.random.wrap_key_data(key_data)  # type: ignore[no-any-return]


def _gaussian_abstract(
    *avals: Any,
    scale: float,
    delta: float | None,
) -> list[Any]:
    del scale, delta
    return list(avals)


_gaussian_p = jax_core.Primitive("gaussian_mechanism")
_gaussian_p.multiple_results = True
_gaussian_p.def_abstract_eval(  # type: ignore[no-untyped-call]
    _gaussian_abstract
)


def _add_gaussian_noise(
    arrays: list[jax.Array],
    scale: float,
    key: jax.Array,
) -> list[jax.Array]:
    keys = jax.random.split(key, len(arrays))
    return [
        array
        + jax.random.normal(
            array_key,
            array.shape,
            dtype=array.dtype,
        )
        * jnp.asarray(scale, dtype=array.dtype)
        for array, array_key in zip(arrays, keys, strict=True)
    ]


def _validate_gaussian_release(
    arrays: list[SensitiveArray],
    scale: float,
    delta: float | None,
) -> float:
    if not arrays:
        raise ValueError("gaussian_mechanism requires at least one array.")
    if not math.isfinite(scale) or scale <= 0:
        raise ValueError("gaussian_mechanism scale must be finite and > 0.")
    if delta is not None and (
        not math.isfinite(delta) or not 0 < delta <= 1
    ):
        raise ValueError("gaussian_mechanism delta must be in (0, 1].")
    if any(array._norm_type != "l2" for array in arrays):
        raise DPError("Gaussian mechanism requires L2 sensitivity.")
    if any(
        not jnp.issubdtype(array._value.dtype, jnp.floating)
        for array in arrays
    ):
        raise TypeError(
            "gaussian_mechanism requires floating array leaves."
        )
    if any(array._accountant is not arrays[0]._accountant for array in arrays[1:]):
        raise DPError(
            "A joint Gaussian release must use one accountant."
        )
    sensitivity = float(joint_l2_max([array._distance for array in arrays]))
    if not math.isfinite(sensitivity) or sensitivity <= 0:
        raise DPError(f"Invalid sensitivity ({sensitivity}).")
    return sensitivity


def _gaussian_mechanism_with_key(
    arrays: list[SensitiveArray],
    scale: float,
    delta: float | None,
    key: jax.Array,
) -> list[jax.Array]:
    sensitivity = _validate_gaussian_release(arrays, scale, delta)
    spend_gaussian(
        arrays[0]._accountant,
        sensitivity=sensitivity,
        scale=scale,
        delta=delta,
    )
    return _add_gaussian_noise(
        [array._value for array in arrays],
        scale=scale,
        key=key,
    )


@egrpc.multifunction
def gaussian_mechanism(
    arrays: list[SensitiveArray],
    scale: float,
    delta: float | None = None,
) -> list[jax.Array]:
    return _gaussian_mechanism_with_key(
        arrays,
        scale,
        delta,
        _fresh_noise_key(),
    )


@gaussian_mechanism.register(remote=False)
def _(
    arrays: list[jax.Array],
    scale: float,
    delta: float | None = None,
) -> list[jax.Array]:
    if not arrays:
        raise ValueError("gaussian_mechanism requires at least one array.")
    if not any(isinstance(array, jax.core.Tracer) for array in arrays):
        raise RuntimeError(
            "Gaussian noise must be generated by the "
            "PrivJail trusted runtime."
        )
    return _gaussian_p.bind(  # type: ignore[no-untyped-call,no-any-return]
        *arrays,
        scale=scale,
        delta=delta,
    )
